# Generated by Django 5.0.4 on 2024-08-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
