# Generated by Django 5.0.4 on 2024-08-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_delete_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
